### ISSUE TITLE
Verify special considerations from Wiki

### ISSUE THREAD

**Issue by FZ69617** [milkboy/WME-ja#35]
The list of all special considerations in Wiki requires verification:
https://wiki.waze.com/wiki/How_Waze_determines_turn_/_keep_/_exit_maneuvers#Special_considerations

Currently it's evident that the following item is not handled by JAI:
* When there are more than two segments less than 45.04°, only the left most segment will be KEEP LEFT, all the rest will be KEEP RIGHT.

I think, that in order to correctly handle it, KEEP (from ja_routing_type) should be devided into KEEP_LEFT and KEEP_RIGHT, and of course instruction guessing algorithm shall support it.

All the other items from Wiki requires deeper analysis.

**Comment by milkboy** [comment]
Yeah. Now it's only shown as "keep", with the angle (keep left might actually be a slight r9ght turn..

**Comment by wlodek76** [comment]
Please check this new patch, it seems that it solves these problems.
https://github.com/milkboy/WME-ja/pull/37

**Comment by FZ69617** [comment]
Another 'consideration' seems to be handled there: https://github.com/milkboy/WME-ja/pull/39

**Comment by FZ69617** [comment]
@milkboy, why did you close this issue? There are lot of the 'special considerations' in the Wiki - have you verified (and added adequate fixes) for them all?

**Comment by milkboy** [comment]
Oh.. Based on the comment by @wlodek76 .. Sorry if I missed something.

**Comment by FZ69617** [comment]
In https://github.com/milkboy/WME-ja/pull/37 @wlodek76 just fixed one 'special consideration' mentioned by me in the issue as the "evident" one.

But we have much more things to consider in Wiki, just another one hopefully fixed by me in https://github.com/milkboy/WME-ja/pull/39 is:
* If the only two segments less than 45.04° overlap each other, neither will get an instruction.

**Comment by milkboy** [comment]
In the case that there are 3 overlapping BC-eligible esits, what is supposed to happen?

**Comment by milkboy** [comment]
Should we also take care of the "locked node" consideration?

**Comment by FZ69617** [comment]
Found [an example from Wiki](https://www.waze.com/editor/?env=row&lon=-0.10969&lat=51.52315&layers=1409&zoom=8&segments=121700427,121697553), but the Warner St does not seem to be a one-way in real. :)
I think, [this case](https://www.waze.com/editor/?env=row&lon=15.50956&lat=51.93970&layers=1413&zoom=8&segments=261278943,261278945) is similar:
![image](https://cloud.githubusercontent.com/assets/6029380/7259527/32aea2da-e864-11e4-8bf4-d805b0cf54e6.png)
As you can see, JAI nicely suggests a "turn right" here - every turn >45° at the junction with >=3 segments will be handled like this one by JAI.

But I think, I don't really know what is a "locked node" mentioned in Wiki, do you know a definition?

**Comment by milkboy** [comment]
Not quite sure. Probably means that any segment to/from that node is locked?

**Comment by FZ69617** [comment]
I think, that almost all special considerations mentioned in Wiki are correctly handled (and even extended) by JAI currently.
And since we are not certain what the only unsupported consideration related to "locked nodes" is about, I think we can safely close this issue as resolved.
What do you think?

**Comment by milkboy** [comment]
Sounds good

**Comment by wlodek76** [comment]
:+1:
