### ISSUE TITLE
No angle on straight going to west

### ISSUE THREAD

**Issue by wlodek76** [milkboy/WME-ja#43]
Missing info on straight and BC angle.

Real example:
https://www.waze.com/pl/editor/?env=row&lon=16.95297&lat=52.30293&layers=388&zoom=5&segments=243207110
![image](https://cloud.githubusercontent.com/assets/7284315/7237882/d47392b8-e79e-11e4-8ba0-52b5779167e3.png)

https://www.waze.com/pl/editor/?env=row&lon=16.97169&lat=52.33636&layers=389&zoom=7&segments=278931458

No angle on simple straight.
![image](https://cloud.githubusercontent.com/assets/7284315/7237783/1798c320-e79e-11e4-99d9-2afee1725d0e.png)

But works ok in oposite direction:
![image](https://cloud.githubusercontent.com/assets/7284315/7237797/308ffd30-e79e-11e4-8a6a-e262786dced1.png)

**Comment by milkboy** [comment]
D'oh?

**Comment by FZ69617** [comment]
Take a look at the "real example" submitted by @wlodek76 - there is missing a white bubble with an angle at node A.

**Comment by wlodek76** [comment]
I should put a clear info, sorry.
But as @FZ69617 wrote no angle info on segment in west direction.

**Comment by milkboy** [comment]
That was a fun problem to track down ;) The duplicate bubble prevention in absolute angle mode was interfering with departure angle display mode, so that depending on the order the angles were selected, it would or would not work.
