### ISSUE TITLE
New waze version - API fail

### ISSUE THREAD

**Issue by CoolCanuck** [milkboy/WME-ja#60]
Today (Dec 15), waze pushed out a new version, thus alerting the user. Error is as follows:

WME Junction Node Fixer has failed to load due to API check: Waze.accelerators.events.listeners.disallowAllConnections

JAI still works.. but the eror is pretty annoying.

**Comment by CoolCanuck** [comment]
Please mark as solved. Issue no longer exists with new Toolbox update.

**Comment by milkboy** [comment]
Closing as invalid
