### ISSUE TITLE
Wrong instruction

### ISSUE THREAD

**Issue by trivia211** [milkboy/WME-ja#67]
https://www.waze.com/hu/editor/?env=row&lon=19.03978&lat=47.54220&zoom=10&lo%20...%20ueFilter=0&segments=255931421

Here JAI indicates a turn left instruction (46°<). Tiles were just updated and there is actually no voice prompt on turning left from here. Tested in Waze Live Map and Waze client.

**Comment by milkboy** [comment]
Not actually sure what is going on here.. According to the turn algorithm flowchart int the wiki https://wiki.waze.com/wiki/How_Waze_determines_turn_/_keep_/_exit_maneuvers (which may not be 100% correct though), it should be a "turn left" instruction...

**Comment by trivia211** [comment]
Probably a bug in Waze then? Would be nice if JAI was aware of these bugs too :)

**Comment by milkboy** [comment]
There may of course have been some minor changes in the logic, but they have to be found by manual testing, which is slow and error prone =/

**Comment by trivia211** [comment]
I see. I'm happy to help if I can. I increased the angle by 1°, we'll see what happens after the next tile update.

**Comment by qwaletee** [comment]
We have seen many cases where Waze does not quite match our angles, but
there is no published standard, and we're 99.9% correct. There's very
little we can do when Waze is occasionally inconsistent. There's surely a
logic too it, but not one we can discern.

**Comment by trivia211** [comment]
Ok. I reported only because the script page said "Routing instruction guessing works mostly, but bug reports with permalink and description are welcome ;)". I don't really understand why the exact algorithm Waze uses is kept secret. Knowing the routing instructions is valuable aid for map editors.

**Comment by milkboy** [comment]
There are probably some unknown logic if the "other" turn is very sharp and/or the connected segment is short.. Maybe.
