### ISSUE TITLE
Need to update for new WME URL

### ISSUE THREAD

**Issue by jcloudm** [milkboy/WME-ja#69]
Hello,

The WME release in the past week has changed the URL. I believe this script needs to change from:

// @include				/^https:\/\/(www|beta)\.waze\.com\/(?!user\/)(.{2,6}\/)?editor\/.*$/

to

// @include				/^https:\/\/(www|beta)\.waze\.com\/(?!user\/)(.{2,6}\/)?editor.*$/

Thanks!

- John (jcloudm in Waze)

**Comment by milkboy** [comment]
Probably fixed by 84dbbd0d7ea51c758f663001fb74fb27cb342457
